// Data loaded from data.json and addresses.json (generated by indexer.py)
let ADDRESSES_RAW = [];
let CEX_WALLETS_SET = new Set();
let CEX_LABELS_MAP = {};
let ADDRESSES = [];
let lastGeneratedAt = null;

function updateFreshnessIndicator() {
  if (!lastGeneratedAt) return;
  const age = Date.now() - lastGeneratedAt.getTime();
  const mins = Math.floor(age / 60000);
  const hours = Math.floor(mins / 60);
  let text, cls;
  if (hours >= 4) { text = `\u26A0 ${hours}h ago`; cls = 'stale-warn'; }
  else if (hours >= 1) { text = `${hours}h ${mins % 60}m ago`; cls = 'stale-ok'; }
  else { text = `${mins}m ago`; cls = 'stale-fresh'; }
  const el = document.getElementById('freshness-indicator');
  el.textContent = text;
  el.className = cls;
}
setInterval(updateFreshnessIndicator, 60000);

async function triggerPipeline() {
  const btn = document.getElementById('refresh-pipeline-btn');
  btn.disabled = true;
  btn.textContent = '...';
  try {
    const resp = await fetch('/api/trigger', { method: 'POST' });
    const data = await resp.json();
    if (resp.status === 202) {
      btn.textContent = '\u23F3';
      btn.title = 'Pipeline running — data will refresh in ~5 min';
      // Poll for completion, then auto-refresh data
      const poll = setInterval(async () => {
        try {
          const s = await fetch('/api/status').then(r => r.json());
          if (!s.running) {
            clearInterval(poll);
            btn.textContent = '\u21BB';
            btn.disabled = false;
            btn.title = 'Trigger fresh data scan from chain';
            // Force immediate data refresh
            const dr = await fetch('data.json?' + Date.now());
            if (dr.ok) {
              const nd = await dr.json();
              if (nd.meta?.generatedAt) {
                const ts = new Date(nd.meta.generatedAt);
                if (!lastGeneratedAt || ts > lastGeneratedAt) {
                  ADDRESSES = nd.addresses.map(d => d.address);
                  buyerData = nd.buyers || [];
                  buyerAddrs = new Set(buyerData.map(b => b.address));
                  stakerData = nd.stakers || [];
                  stakerMap = {}; for (const s of stakerData) stakerMap[s.address] = s;
                  for (const d of nd.addresses) { ingestAddress(d); }
                  lastGeneratedAt = ts;
                  updateStats(); updateBuyerStats(); updateStakerStats();
                  scheduleRender(); updateFreshnessIndicator();
                }
              }
            }
          }
        } catch(e) {}
      }, 15000);
    } else if (resp.status === 409) {
      btn.textContent = '\u23F3';
      btn.title = 'Pipeline already running';
      setTimeout(() => { btn.textContent = '\u21BB'; btn.disabled = false; }, 5000);
    } else if (resp.status === 429) {
      btn.textContent = '\u21BB';
      btn.disabled = false;
      btn.title = `Cooldown: retry in ${data.retry_after}s`;
    }
  } catch(e) {
    btn.textContent = '\u21BB';
    btn.disabled = false;
    btn.title = 'Trigger failed — check connection';
  }
}


// ── USER LABELS ───────────────────────────────────────────────────────────────
const LABELS_KEY = 'kat_farmer_labels';
let LABELS = {};
function saveLabels() { try { localStorage.setItem(LABELS_KEY, JSON.stringify(LABELS)); } catch(e) {} }
function loadLabelsFromStorage() {
  try { const raw = localStorage.getItem(LABELS_KEY); if (raw) Object.assign(LABELS, JSON.parse(raw)); } catch(e) {}
}
loadLabelsFromStorage();


// ADDRESSES populated from data.json in main()

// ── STATE ────────────────────────────────────────────────────────────────────
const results = {};
let sortCol = 'claimed';
let sortDir = -1;
let filterText = '';
let filterStatus = '';
let minAmount = 0;
let topN = 0;
let renderPending = false;

// ── URL STATE ─────────────────────────────────────────────────────────────────
(function initFromURL() {
  const sp = new URLSearchParams(location.search);
  if (sp.get('status')) filterStatus = sp.get('status');
  if (sp.get('q'))      filterText   = sp.get('q');
  if (sp.get('sort'))   sortCol      = sp.get('sort');
  if (sp.get('dir'))    sortDir      = 1;
  if (sp.get('min'))    minAmount    = +sp.get('min') || 0;
  if (sp.get('top'))    topN         = +sp.get('top') || 0;
})();

function pushState() {
  const p = new URLSearchParams();
  if (filterStatus)   p.set('status', filterStatus);
  if (filterText)     p.set('q', filterText);
  if (sortCol !== 'claimed') p.set('sort', sortCol);
  if (sortDir !== -1) p.set('dir', '1');
  if (minAmount > 0)  p.set('min', String(minAmount));
  if (topN > 0)       p.set('top', String(topN));
  const qs = p.toString();
  history.replaceState(null, '', qs ? '?' + qs : location.pathname);
}

// ── UTILITIES ─────────────────────────────────────────────────────────────────
function escapeHtml(text) {
  const map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
  return text.replace(/[&<>"']/g, c => map[c]);
}


// ---- KAT → USD annotation ----
let katPriceUsd = null;
const _katCache = {}; // id -> { kat, baseSub, prefix? }
const KAT_USD_SUBS = {
  'stat-claimed':         'stat-claimed-sub',
  'stat-staked':          'stat-staked-sub',
  'sstat-total-staked':   'sstat-total-sub',
  'sstat-vkat':           'sstat-vkat-sub',
  'sstat-avkat':          'sstat-avkat-sub',
  'sstat-median-stake':   'sstat-median-stake-sub',
};
function fmtUsd(v) {
  if (!(v > 0)) return '';
  if (v >= 1e9) return '$' + (v / 1e9).toFixed(2) + 'B';
  if (v >= 1e6) return '$' + (v / 1e6).toFixed(2) + 'M';
  if (v >= 1e3) return '$' + (v / 1e3).toFixed(1) + 'K';
  if (v >= 1)   return '$' + v.toFixed(2);
  return '$' + v.toFixed(4);
}
function setKatStatSub(valueId, subId, kat, baseSub) {
  _katCache[valueId] = { kat, baseSub: baseSub || '' };
  refreshOneKatSub(valueId);
}
function refreshOneKatSub(valueId) {
  const c = _katCache[valueId];
  if (!c) return;
  const subId = KAT_USD_SUBS[valueId] || (valueId === 'supply-hero-total' ? 'supply-hero-total' : null);
  const el = subId ? document.getElementById(subId) : null;
  if (!el) return;
  const usd = katPriceUsd ? fmtUsd(c.kat * katPriceUsd) : '';
  if (valueId === 'supply-hero-total') {
    const parts = [];
    if (c.prefix) parts.push(c.prefix);
    if (usd) parts.push(usd);
    if (c.baseSub) parts.push(c.baseSub);
    el.textContent = parts.join(' · ');
    return;
  }
  const parts = [];
  if (usd) parts.push(usd);
  if (c.baseSub) parts.push(c.baseSub);
  el.textContent = parts.join(' · ');
}
function refreshAllKatSubs() {
  Object.keys(_katCache).forEach(refreshOneKatSub);
}
async function fetchKatPrice() {
  try {
    const cached = JSON.parse(localStorage.getItem('kat_price_usd') || 'null');
    if (cached && typeof cached.usd === 'number' && cached.usd > 0) {
      katPriceUsd = cached.usd;
      refreshAllKatSubs();
      if (Date.now() - (cached.ts || 0) < 600000) return; // fresh; skip refetch
    }
    const resp = await fetch('https://api.coingecko.com/api/v3/simple/price?ids=katana-network-token&vs_currencies=usd');
    if (!resp.ok) return;
    const j = await resp.json();
    const usd = j && j['katana-network-token'] && j['katana-network-token'].usd;
    if (typeof usd === 'number' && usd > 0) {
      katPriceUsd = usd;
      try { localStorage.setItem('kat_price_usd', JSON.stringify({ usd, ts: Date.now() })); } catch(e) {}
      refreshAllKatSubs();
    }
  } catch (e) {
    console.warn('KAT price fetch failed:', e && e.message);
  }
}

function fmtNum(n, dp = 2) {
  if (n === null || n === undefined || isNaN(n)) return '—';
  if (n === 0) return '—';
  if (n < 0.01) return '<0.01';
  if (n >= 1e9) return (n / 1e9).toFixed(2) + 'B';
  if (n >= 1e6) return (n / 1e6).toFixed(2) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(1) + 'K';
  return n.toLocaleString('en-US', { minimumFractionDigits: dp, maximumFractionDigits: dp });
}



// ── CLASSIFICATION ────────────────────────────────────────────────────────────
function retainedPct(d) {
  // Balance-based: what fraction of claimed tokens are still held?
  // Includes KAT balance + staked (vKAT + avKAT) + ETH-side KAT balance + DeFi positions still holding
  if (d.claimed === 0) return 100;
  const defiHeld = (d.defiPositions || []).filter(p => p.held).reduce((s, p) => s + p.amount, 0);
  const held = (d.balance || 0) + (d.staked || d.avkat || 0) + (d.ethBalance || 0) + defiHeld;
  return Math.max(0, Math.min(100, (held / d.claimed) * 100));
}

function classify(d) {
  if (d.claimed === 0) return 'inactive';
  const retained = retainedPct(d);
  if (retained < 50)  return 'farmer';
  if (retained < 95)  return 'partial';
  return 'hodler';
}

function dumpPct(d) {
  if (d.claimed === 0) return 0;
  return 100 - retainedPct(d);
}

function ingestAddress(d) {
  const sk = stakerMap[d.address];
  d.staked = sk ? (sk.vkatAmount || 0) + (sk.avkatAmount || 0) : (d.avkat || 0);
  d.status = classify(d);
  results[d.address] = { ...d, _loading: false };
}

// ── FILTER / SORT ─────────────────────────────────────────────────────────────
function getFilteredRows() {
  let rows = Object.values(results).filter(d => !d._loading);
  if (filterText)   rows = rows.filter(d => d.address.includes(filterText.toLowerCase()));
  if (filterStatus === 'staked') rows = rows.filter(d => (d.staked || d.avkat || 0) > 0);
  else if (filterStatus) rows = rows.filter(d => d.status === filterStatus);
  else rows = rows.filter(d => d.status !== 'inactive'); // hidden by default — click "Never Claimed" card to show
  if (minAmount > 0) rows = rows.filter(d => (d.claimed || 0) >= minAmount);

  rows.sort((a, b) => {
    let av, bv;
    if (sortCol === 'dumpPct')       { av = dumpPct(a); bv = dumpPct(b); }
    else if (sortCol === 'rank')     { av = dumpPct(a); bv = dumpPct(b); return bv - av; }
    else if (sortCol === 'status')   { av = a.status; bv = b.status; return sortDir * av.localeCompare(bv); }
    else if (sortCol === 'address')  { av = a.address; bv = b.address; return sortDir * av.localeCompare(bv); }
    else { av = a[sortCol] || 0; bv = b[sortCol] || 0; }
    return sortDir * (av - bv);
  });

  if (topN > 0) rows = rows.slice(0, topN);
  return rows;
}

// ── RENDER ─────────────────────────────────────────────────────────────────────
function badge(status, avkat) {
  const map = {
    farmer:   ['badge-farmer',   'DUMPED',   'Sold or sent >50% of claimed KAT'],
    partial:  ['badge-partial',  'PARTIAL',  'Sold or sent 5–50% of claimed KAT'],
    hodler:   ['badge-hodler',   'HODLER',   'Sold or sent <5% of claimed KAT'],
    inactive: ['badge-inactive', 'INACTIVE', 'Never claimed Merkl rewards'],
  };
  const [cls, label, tip] = map[status] || map.inactive;
  let html = `<span class="badge ${cls}" data-tip="${tip}">${label}</span>`;
  if (avkat > 0) html += ` <span class="badge badge-staked" data-tip="Has deposited KAT into avKAT auto-compounding vault">STAKED</span>`;
  return html;
}

function shortAddr(a) {
  return `<b>${a.slice(0, 6)}</b><span class="addr-ellipsis">…</span>${a.slice(-4)}`;
}
function getLabelEntry(addr) {
  // Returns { label, chain } or null. Handles legacy string LABELS from localStorage.
  const a = addr.toLowerCase();
  const raw = LABELS[addr] || LABELS[a] || CEX_LABELS_MAP[a] || null;
  if (!raw) return null;
  if (typeof raw === 'string') return { label: raw, chain: 'kat' };
  return raw;
}
function getLabel(addr) {
  const entry = getLabelEntry(addr);
  return entry ? entry.label : null;
}
function tinyAddrDisplay(addr) {
  const label = getLabel(addr);
  if (label) return `<span class="addr-label" title="${addr}">${escapeHtml(label)}</span>`;
  return shortAddr(addr);
}
function addrDisplay(addr) {
  const label = getLabel(addr);
  const short = shortAddr(addr);
  if (!label) return `<span title="${addr}">${short}</span>`;
  const truncated = label.length > 40 ? label.slice(0, 40) + '…' : label;
  return `<span title="${addr}">${short}<span class="addr-sep">·</span><span class="addr-label">${escapeHtml(truncated)}</span></span>`;
}

// ── CELL RENDER HELPERS ────────────────────────────────────────────────────────
function renderSentCell(d) {
  if (d._loading) return '<span class="cell-pending">…</span>';
  const transferred = d.transferred || 0;
  const transferredTo = d.transferredTo || [];
  const sentHeld = d.sentHeld || 0;
  const sentHeldTo = d.sentHeldTo || [];
  const bridged = d.bridged || 0;
  const cexSent = d.cexSent || 0;
  const cexDests = d.cexDests || [];

  const visibleAddrs = transferredTo.slice(0, 3);
  const extraAddrs   = transferredTo.slice(3);
  const sentChips = visibleAddrs.map(a =>
    `<a class="addr-tiny" href="https://katanascan.com/address/${a}" target="_blank" rel="noopener" title="${a}">${tinyAddrDisplay(a)}</a>`
  ).join(' ');
  const moreChip  = extraAddrs.length ? ` <span class="addr-more" title="${extraAddrs.join('\n')}">+${extraAddrs.length} more</span>` : '';

  const heldChips = sentHeldTo.slice(0, 2).map(a =>
    `<a class="addr-tiny" href="https://katanascan.com/address/${a}" target="_blank" rel="noopener" title="${a} (still holding)">${tinyAddrDisplay(a)}</a>`
  ).join(' ');
  const heldMore = sentHeldTo.length > 2 ? ` <span class="addr-more">+${sentHeldTo.length - 2} more</span>` : '';

  const hasDumped  = d.claimed > 0 && transferred > 0.01;
  const hasHeld    = d.claimed > 0 && sentHeld > 0.01;
  const hasBridged = bridged > 0.01;
  if (!hasDumped && !hasHeld && !hasBridged) return '—';
  let html = '';
  if (hasDumped) {
    html += `<span class="num-orange">${fmtNum(transferred)}</span>`;
    if (sentChips) html += `<br>${sentChips}${moreChip}`;
  }
  if (hasHeld) {
    if (hasDumped) html += ' ';
    html += `<span class="num-green" title="Sent to wallets still holding the KAT — excluded from Dump %">${fmtNum(sentHeld)} held</span>`;
    if (heldChips) html += `<br>${heldChips}${heldMore}`;
  }
  if (hasBridged) {
    if (hasDumped || hasHeld) html += '<br>';
    const ethChip = '<span class="chain-badge chain-eth">◆ ETH</span>';
    const ethBal = d.ethBalance || 0;
    if (cexSent > 0.01) {
      const names = [...new Set(cexDests.map(d => { const e = CEX_LABELS_MAP[d.toLowerCase()]; return e ? (typeof e === 'string' ? e : e.label) : null; }).filter(Boolean))];
      const cexLabel = names.length === 1 ? names[0] : 'CEX';
      html += `<span class="num-red" title="Bridged via LayerZero to ETH mainnet, then deposited to ${cexLabel}">${ethChip}${fmtNum(bridged)} → ${cexLabel}</span>`;
    } else if (ethBal > 0.01) {
      html += `<span class="num-green" title="Bridged ${fmtNum(bridged)} KAT to ETH mainnet — still holding ${fmtNum(ethBal)} on ETH">${ethChip}${fmtNum(ethBal)} held on ETH</span>`;
    } else {
      html += `<span class="num-red" title="Bridged ${fmtNum(bridged)} KAT to ETH mainnet — no longer holding on ETH">${ethChip}${fmtNum(bridged)} bridged → sold</span>`;
    }
  }
  return html;
}

function renderBalanceCell(d) {
  if (d._loading) return '<span class="cell-pending">…</span>';
  return d.balance > 0.01 ? `<span class="num-green">${fmtNum(d.balance)}</span>` : '—';
}

function renderStakedCell(d) {
  if (d._loading) return '<span class="cell-pending">…</span>';
  const sk = stakerMap[d.address];
  const vk = sk ? (sk.vkatAmount || 0) : 0;
  const ak = sk ? (sk.avkatAmount || 0) : (d.avkat || 0);
  const total = vk + ak;
  if (total < 0.01) return '—';
  let parts = [];
  if (vk > 0.01) parts.push(fmtNum(vk) + ' vKAT');
  if (ak > 0.01) parts.push(fmtNum(ak) + ' avKAT');
  return `<span class="num-blue">${parts.join(' + ')}</span>`;
}

function renderPctCell(d) {
  if (d._loading) return '<span class="cell-pending">…</span>';
  if (d.claimed <= 0) return '—';
  const pct = dumpPct(d);
  return `<span class="${pct > 50 ? 'num-red' : pct > 5 ? 'num-yellow' : pct > 0 ? 'num-green' : 'num-dim'}">${pct.toFixed(1)}%</span>`;
}

function renderTable() {
  if (document.querySelector('.label-input')) return;
  renderPending = false;
  const allRows = Object.values(results);
  const filtered = getFilteredRows();

  const countText = filterText || filterStatus || minAmount > 0 || topN > 0
    ? `${filtered.length.toLocaleString()} / ${allRows.length.toLocaleString()}`
    : `${allRows.length.toLocaleString()} addresses`;
  document.getElementById('table-count').textContent = countText;

  const tbody = document.getElementById('table-body');

  if (filtered.length === 0 && allRows.length > 0) {
    tbody.innerHTML = '<tr class="loading-row"><td colspan="10">No matching addresses</td></tr>';
    return;
  }
  if (allRows.length === 0) return;

  tbody.innerHTML = filtered.map((d, i) => {
    const moved = d.moved || 0;
    const rowCls = d.status === 'farmer'   ? 'row-farmer'
                 : d.status === 'hodler'   ? 'row-hodler'
                 : d.status === 'inactive' ? 'row-inactive'
                 : '';

    const pending = d._loading ? '<span class="cell-pending">…</span>' : '—';
    const errIcon = d._error ? ' <span title="RPC fetch failed for this address" style="color:var(--yellow);font-size:0.65rem">⚠</span>' : '';

    return `<tr class="${rowCls}">
      <td>${i + 1}</td>
      <td class="addr-cell" onclick="editLabel(this,'${d.address}')" title="Click to label">
        ${addrDisplay(d.address)}${errIcon}${buyerAddrs.has(d.address) ? '<span class="badge-bought" data-tip="Also bought KAT on DEX or CEX">bought</span>' : ''}
      </td>
      <td>${d._loading ? '' : badge(d.status, d.avkat)}</td>
      <td class="num">${d._loading ? pending : (d.claimed > 0 ? `<span class="num-yellow">${fmtNum(d.claimed)}</span>` : '—')}</td>
      <td class="num num-detail">${renderSentCell(d)}</td>
      <td class="num">${d._loading ? pending : (moved > 0.01 ? `<span class="num-red">${fmtNum(moved)}</span>` : '—')}</td>
      <td class="num">${renderBalanceCell(d)}</td>
      <td class="num">${renderStakedCell(d)}</td>
      <td class="num">${renderPctCell(d)}</td>
      <td>
        <div class="ext-links">
          <a class="ext-link" href="https://katanascan.com/address/${d.address}" target="_blank" rel="noopener">explr</a>
          <a class="ext-link" href="https://app.merkl.xyz/users/${d.address}" target="_blank" rel="noopener">merkl</a>
          <a class="ext-link" href="#" onclick="navigator.clipboard.writeText('${d.address}');this.textContent='✓';setTimeout(()=>this.textContent='⎘',1200);return false;" title="Copy address">⎘</a>
        </div>
      </td>
    </tr>`;
  }).join('');
}

function scheduleRender() {
  if (!renderPending) {
    renderPending = true;
    requestAnimationFrame(renderTable);
  }
}

function updateStats() {
  const all            = Object.values(results).filter(d => !d._loading);
  const n              = ADDRESSES.length;
  const totalClaimed   = all.reduce((s, d) => s + d.claimed, 0);
  const inactiveCount  = all.filter(d => d.status === 'inactive').length;
  const farmers        = all.filter(d => d.status === 'farmer').length;
  const hodlers        = all.filter(d => d.status === 'hodler').length;
  const partials       = all.filter(d => d.status === 'partial').length;

  document.getElementById('stat-total').textContent        = `${Object.keys(CEX_LABELS_MAP).length + Object.keys(LABELS).length} labelled`;
  document.getElementById('stat-claimed').textContent  = fmtNum(totalClaimed, 0);
  setKatStatSub('stat-claimed', 'stat-claimed-sub', totalClaimed, '');
  document.getElementById('stat-claimable').textContent    = partials.toLocaleString();
  document.getElementById('stat-claimable-sub').textContent = n > 0 ? `${((partials / n) * 100).toFixed(1)}% of ${n}` : '';
  document.getElementById('stat-hodlers').textContent      = hodlers.toLocaleString();
  document.getElementById('stat-hodlers-sub').textContent  = n > 0 ? `${((hodlers / n) * 100).toFixed(1)}% of ${n}` : '';
  const stakerCount  = all.filter(d => (d.staked || d.avkat || 0) > 0).length;
  const totalStaked  = all.reduce((s, d) => s + (d.staked || d.avkat || 0), 0);
  document.getElementById('stat-staked').textContent      = fmtNum(totalStaked, 0);
  setKatStatSub('stat-staked', 'stat-staked-sub', totalStaked, stakerCount > 0 ? `${stakerCount} stakers` : '');
  document.getElementById('stat-inactive').textContent    = inactiveCount.toLocaleString();
  document.getElementById('stat-inactive-sub').textContent = inactiveCount > 0 ? `never claimed` : '';
}

// ── COPY ──────────────────────────────────────────────────────────────────────
function copyAddr(cell, addr) {
  navigator.clipboard.writeText(addr).then(() => {
    cell.classList.add('copied');
    setTimeout(() => cell.classList.remove('copied'), 1200);
  });
}

function editLabel(cell, addr) {
  if (cell.querySelector('.label-input')) return;
  let committed = false;
  const entry = getLabelEntry(addr);
  const current = entry ? entry.label : '';
  const chain = entry ? entry.chain : 'kat';
  const input = document.createElement('input');
  input.type = 'text';
  input.className = 'label-input';
  input.value = current;
  input.placeholder = 'label…';
  input.title = addr;

  function restoreCell() {
    cell.innerHTML = addrDisplay(addr);
  }
  function commit() {
    if (committed) return;
    committed = true;
    const val = input.value.trim();
    if (val) LABELS[addr] = { label: val, chain };
    else delete LABELS[addr];
    saveLabels();
    restoreCell();
    scheduleRender();
    renderBuyersTable();
    renderStakersTable();
  }
  function cancel() {
    if (committed) return;
    committed = true;
    restoreCell();
    scheduleRender();
    renderBuyersTable();
    renderStakersTable();
  }

  input.addEventListener('keydown', e => {
    if (e.key === 'Enter') { e.preventDefault(); commit(); }
    if (e.key === 'Escape') { e.preventDefault(); cancel(); }
  });
  input.addEventListener('blur', commit);

  cell.innerHTML = '';
  cell.appendChild(input);
  input.focus();
  input.select();
}

// ── EXPORT ────────────────────────────────────────────────────────────────────
function exportLabels() {
  const blob = new Blob([JSON.stringify(LABELS, null, 2)], { type: 'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'labels.json';
  a.click();
  URL.revokeObjectURL(a.href);
}

function showAddressbook() {
  // Build merged map: addr → { addr, label, chain, source }
  const map = {};
  Object.entries(CEX_LABELS_MAP).forEach(([addr, entry]) => {
    const a = addr.toLowerCase();
    const label = typeof entry === 'string' ? entry : entry.label;
    const chain = typeof entry === 'string' ? 'kat' : entry.chain;
    map[a] = { addr: a, label, chain, source: 'cex' };
  });
  // LABELS override CEX_LABELS_MAP
  Object.entries(LABELS).forEach(([addr, entry]) => {
    const a = addr.toLowerCase();
    const label = typeof entry === 'string' ? entry : entry.label;
    const chain = typeof entry === 'string' ? 'kat' : (entry.chain || 'kat');
    const isCexOverride = !!map[a];
    map[a] = { addr: a, label, chain, source: isCexOverride ? 'override' : 'user' };
  });
  const sorted = Object.values(map).sort((a, b) => a.label.localeCompare(b.label));

  function chainPill(chain) {
    const cls = chain === 'eth' ? 'chain-pill-eth' : 'chain-pill-kat';
    return `<span class="chain-pill ${cls}">${chain.toUpperCase()}</span>`;
  }

  const rows = sorted.map(e => {
    const r = results[e.addr];
    const bal = r ? fmtNum(r.balance) : '—';
    const overrideTag = e.source === 'override' ? '<span class="ab-override" title="Custom override of CEX label">✎</span>' : '';
    return `<tr data-addr="${e.addr}">` +
      `<td class="ab-label"><b>${escapeHtml(e.label)}</b>${overrideTag}</td>` +
      `<td class="ab-addr"><a href="https://katanascan.com/address/${e.addr}" target="_blank" rel="noopener">${e.addr}</a></td>` +
      `<td class="ab-chain">${chainPill(e.chain)}</td>` +
      `<td class="ab-bal">${bal}</td>` +
      `</tr>`;
  }).join('');

  const addRow = `<tr class="ab-add-row">` +
    `<td><input type="text" id="ab-new-label" placeholder="Label…"></td>` +
    `<td><input type="text" id="ab-new-addr" placeholder="0x…" style="width:100%"></td>` +
    `<td class="ab-chain"><span class="chain-pill chain-pill-kat" id="ab-new-chain" style="cursor:pointer">KAT</span></td>` +
    `<td><button class="ab-add-btn" id="ab-add-btn">Add</button></td>` +
    `</tr>`;

  document.getElementById('addressbook-body').innerHTML =
    `<table><thead><tr><th>Label</th><th>Address</th><th>Chain</th><th style="text-align:right">KAT Balance</th></tr></thead>` +
    `<tbody>${rows}${addRow}</tbody></table>`;

  // Inline label editing
  document.querySelectorAll('#addressbook-body .ab-label').forEach(td => {
    td.addEventListener('click', () => {
      if (td.querySelector('.label-input')) return;
      const tr = td.closest('tr');
      const addr = tr.dataset.addr;
      const entry = getLabelEntry(addr);
      const current = entry ? entry.label : '';
      const chain = entry ? entry.chain : 'kat';
      let committed = false;
      const input = document.createElement('input');
      input.type = 'text';
      input.className = 'label-input';
      input.value = current;
      input.placeholder = 'label…';
      function commit() {
        if (committed) return;
        committed = true;
        const val = input.value.trim();
        if (val) LABELS[addr] = { label: val, chain };
        else delete LABELS[addr];
        saveLabels();
        showAddressbook();
      }
      input.addEventListener('keydown', e => {
        if (e.key === 'Enter') { e.preventDefault(); commit(); }
        if (e.key === 'Escape') { e.preventDefault(); committed = true; showAddressbook(); }
      });
      input.addEventListener('blur', commit);
      td.innerHTML = '';
      td.appendChild(input);
      input.focus();
      input.select();
    });
  });

  // Chain toggle
  document.querySelectorAll('#addressbook-body tr[data-addr] .chain-pill').forEach(pill => {
    pill.style.cursor = 'pointer';
    pill.addEventListener('click', () => {
      const tr = pill.closest('tr');
      const addr = tr.dataset.addr;
      const entry = getLabelEntry(addr);
      if (!entry) return;
      const newChain = entry.chain === 'eth' ? 'kat' : 'eth';
      LABELS[addr] = { label: entry.label, chain: newChain };
      saveLabels();
      showAddressbook();
    });
  });

  // Add new entry
  const newChainPill = document.getElementById('ab-new-chain');
  let newChain = 'kat';
  newChainPill.addEventListener('click', () => {
    newChain = newChain === 'kat' ? 'eth' : 'kat';
    newChainPill.textContent = newChain.toUpperCase();
    newChainPill.className = `chain-pill chain-pill-${newChain}`;
  });
  document.getElementById('ab-add-btn').addEventListener('click', () => {
    const label = document.getElementById('ab-new-label').value.trim();
    const addr = document.getElementById('ab-new-addr').value.trim().toLowerCase();
    if (!label || !addr || !addr.startsWith('0x')) return;
    LABELS[addr] = { label, chain: newChain };
    saveLabels();
    showAddressbook();
    scheduleRender();
  });
  // Submit on Enter in the add row inputs
  ['ab-new-label', 'ab-new-addr'].forEach(id => {
    document.getElementById(id).addEventListener('keydown', e => {
      if (e.key === 'Enter') { e.preventDefault(); document.getElementById('ab-add-btn').click(); }
    });
  });

  document.getElementById('addressbook-modal').classList.add('open');
  document.body.style.overflow = 'hidden';
}

function exportCSV() {
  const rows = getFilteredRows();
  const header = ['Address','KAT Claimed','KAT Balance','KAT Staked','KAT Sold','KAT Sent','Sent To','DeFi Positions','Dump %','Status'];
  const lines  = rows.map(d => [
    d.address,
    d.claimed.toFixed(6),
    d.balance.toFixed(6),
    d.avkat.toFixed(6),
    (d.moved || 0).toFixed(6),
    (d.transferred || 0).toFixed(6),
    (d.transferredTo || []).join('|'),
    (d.defiPositions || []).map(p => `${p.amount} ${p.type} (${p.address})`).join('|'),
    dumpPct(d).toFixed(2),
    d.status
  ].join(','));
  const csv      = [header.join(','), ...lines].join('\n');
  const blob     = new Blob([csv], { type: 'text/csv' });
  const url      = URL.createObjectURL(blob);
  const filename = `kat-farmer${filterStatus ? '-' + filterStatus : ''}.csv`;
  Object.assign(document.createElement('a'), { href: url, download: filename }).click();
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}

// ── CUSTOM SELECT HELPERS ─────────────────────────────────────────────────────
function syncSelectUI(id, value) {
  const select = document.getElementById(id);
  const btn    = document.getElementById(id + '-btn');
  const menu   = document.getElementById(id + '-menu');
  if (!btn || !menu) return;
  select.value = String(value);
  const items = menu.querySelectorAll('li');
  let activeItem = null;
  items.forEach(li => {
    const match = li.dataset.value === String(value);
    li.classList.toggle('selected', match);
    if (match) activeItem = li;
  });
  if (activeItem) btn.querySelector('.custom-select-label').textContent = activeItem.textContent;
}

function initCustomSelects() {
  document.querySelectorAll('.custom-select-wrap').forEach(wrap => {
    const id  = wrap.id.replace('-wrap', '');
    const btn = document.getElementById(id + '-btn');
    const menu = document.getElementById(id + '-menu');
    const sel  = document.getElementById(id);
    // Mark first item selected by default
    const first = menu.querySelector('li');
    if (first) first.classList.add('selected');
    btn.addEventListener('click', e => {
      e.stopPropagation();
      document.querySelectorAll('.custom-select-wrap.open').forEach(w => { if (w !== wrap) w.classList.remove('open'); });
      wrap.classList.toggle('open');
    });
    menu.querySelectorAll('li').forEach(li => {
      li.addEventListener('click', () => {
        syncSelectUI(id, li.dataset.value);
        sel.dispatchEvent(new Event('change'));
        wrap.classList.remove('open');
      });
    });
  });
  document.addEventListener('click', () => {
    document.querySelectorAll('.custom-select-wrap.open').forEach(w => w.classList.remove('open'));
  });
}

// ── BUYERS STATE ─────────────────────────────────────────────────────────────
let buyerData        = [];
let buyerAddrs       = new Set();
let buyerCatFilter   = '';
let buyerStakeFilter = '';
let buyerBotFilter   = true;   // hide bots by default
let buyerFilterText  = '';
let buyerSortCol     = 'katNet';
let buyerSortDir     = -1;

function getBuyerFilteredRows() {
  let rows = buyerData.slice();
  if (buyerFilterText)                    rows = rows.filter(b => b.address.includes(buyerFilterText));
  if (buyerCatFilter === 'pure_buyer')    rows = rows.filter(b => b.category === 'pure_buyer');
  if (buyerCatFilter === 'airdrop_buyer') rows = rows.filter(b => b.category === 'airdrop_buyer');
  if (buyerStakeFilter === 'staked')      rows = rows.filter(b => b.staked);
  if (buyerStakeFilter === 'unstaked')    rows = rows.filter(b => !b.staked);
  if (buyerBotFilter)                     rows = rows.filter(b => (b.txCount || 0) < 100);
  rows.sort((a, b) => {
    let av = a[buyerSortCol], bv = b[buyerSortCol];
    if (typeof av === 'boolean') { av = av ? 1 : 0; bv = bv ? 1 : 0; }
    if (typeof av === 'string')  return buyerSortDir * av.localeCompare(bv);
    return buyerSortDir * ((av || 0) - (bv || 0));
  });
  return rows;
}

function updateBuyerStats() {
  const all    = buyerData;
  const pure   = all.filter(b => b.category === 'pure_buyer').length;
  const airdrop= all.filter(b => b.category === 'airdrop_buyer').length;
  const staked = all.filter(b => b.staked).length;
  const vkat   = all.filter(b => b.stakedVKAT).length;
  const avkat  = all.filter(b => b.stakedAvKAT).length;
  document.getElementById('bstat-total').textContent   = all.length.toLocaleString();
  document.getElementById('bstat-pure').textContent    = pure.toLocaleString();
  document.getElementById('bstat-airdrop').textContent = airdrop.toLocaleString();
  document.getElementById('bstat-staked').textContent  = staked.toLocaleString();
  document.getElementById('bstat-staked-sub').textContent = all.length > 0 ? `${((staked / all.length) * 100).toFixed(1)}% of buyers` : '';
  document.getElementById('bstat-vkat').textContent    = vkat.toLocaleString();
  document.getElementById('bstat-avkat').textContent   = avkat.toLocaleString();
}

function renderBuyersTable() {
  if (document.querySelector('.label-input')) return;
  const rows    = getBuyerFilteredRows();
  const countEl = document.getElementById('buyer-table-count');
  countEl.textContent = (buyerFilterText || buyerCatFilter || buyerStakeFilter || buyerBotFilter)
    ? `${rows.length} / ${buyerData.length} buyers`
    : `${buyerData.length.toLocaleString()} buyers`;

  const tbody = document.getElementById('buyer-table-body');
  if (buyerData.length === 0) {
    tbody.innerHTML = '<tr class="loading-row"><td colspan="9">No buyer data — run: python3 indexer.py</td></tr>';
    return;
  }
  if (rows.length === 0) {
    tbody.innerHTML = '<tr class="loading-row"><td colspan="9">No matching buyers</td></tr>';
    return;
  }

  const sourceBadge = s => {
    const map = { dex: ['badge-source-dex', 'DEX', 'Bought via Sushiswap DEX pool'], cex: ['badge-source-cex', 'CEX', 'Transferred in from a centralised exchange'], both: ['badge-source-both', 'DEX+CEX', 'Both DEX and CEX sources detected'] };
    const [cls, label, tip] = map[s] || ['badge-inactive', s, ''];
    return `<span class="badge ${cls}" data-tip="${tip}">${label}</span>`;
  };

  tbody.innerHTML = rows.map((b, i) => {
    const airdropBadge = b.category === 'airdrop_buyer'
      ? '<span class="badge-airdrop" data-tip="Also received pre-TGE farming rewards">airdrop</span>' : '';
    const vkatCell  = b.vkatAmount  > 0 ? `<span class="num-blue">${fmtNum(b.vkatAmount)}</span>` : '<span class="dash-unstaked">—</span>';
    const avkatCell = b.avkatAmount > 0 ? `<span class="num-blue">${fmtNum(b.avkatAmount)}</span>` : '<span class="dash-unstaked">—</span>';
    return `<tr>
      <td>${i + 1}</td>
      <td class="addr-cell" onclick="editLabel(this,'${b.address}')" title="Click to label">
        ${addrDisplay(b.address)}${airdropBadge}
      </td>
      <td>${b.category === 'pure_buyer' ? '<span class="badge badge-pure-buyer" data-tip="No pre-TGE airdrop allocation — pure market buyer">Buyer</span>' : '<span class="badge badge-airdrop-buyer" data-tip="Also received pre-TGE farming rewards">Airdrop+</span>'}</td>
      <td>${sourceBadge(b.buySource)}</td>
      <td class="num"><span class="num-blue">${fmtNum(b.katNet)}</span></td>
      <td class="num">${b.txCount}</td>
      <td class="num">${vkatCell}</td>
      <td class="num">${avkatCell}</td>
      <td>
        <div class="ext-links">
          <a class="ext-link" href="https://katanascan.com/address/${b.address}" target="_blank" rel="noopener">explr</a>
          <a class="ext-link" href="#" onclick="navigator.clipboard.writeText('${b.address}');this.textContent='✓';setTimeout(()=>this.textContent='⎘',1200);return false;" title="Copy address">⎘</a>
        </div>
      </td>
    </tr>`;
  }).join('');
}

function exportBuyerCSV() {
  const rows   = getBuyerFilteredRows();
  const header = ['Address','Category','Buy Source','KAT Held (On-Chain)','Net Bought','KAT Received','KAT Sold','# Buys','vKAT','avKAT'];
  const lines  = rows.map(b => [
    b.address, b.category, b.buySource,
    (b.katHeld||0).toFixed(6), b.katNet.toFixed(6), b.katReceived.toFixed(6), (b.katSold||0).toFixed(6), b.txCount,
    (b.vkatAmount||0).toFixed(6),
    (b.avkatAmount||0).toFixed(6),
  ].join(','));
  const csv  = [header.join(','), ...lines].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);
  Object.assign(document.createElement('a'), { href: url, download: 'kat-buyers.csv' }).click();
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}

// ── STAKERS STATE ─────────────────────────────────────────────────────────────
let stakerData       = [];
let stakerMap        = {};
let stakerFilterText = '';
let stakerSortCol    = 'totalStaked';
let stakerSortDir    = -1;
let circSupply       = 0;
let onChainVkat      = 0;
let onChainAvkat     = 0;
let onChainTotal     = 0;
let vkatHolders      = 0;   // meta.vkatHolders — addresses holding a vKAT lock
let avkatHolders     = 0;   // meta.avkatHolders — addresses with avKAT balance > 0
let stakerCountMeta  = 0;   // meta.stakerCount — unique vKAT∪avKAT holders

function getStakerFilteredRows() {
  let rows = stakerData.slice();
  if (stakerFilterText) rows = rows.filter(s => s.address.includes(stakerFilterText));
  rows.sort((a, b) => {
    let av = a[stakerSortCol], bv = b[stakerSortCol];
    if (stakerSortCol === 'type') {
      av = stakerType(a); bv = stakerType(b);
      return stakerSortDir * av.localeCompare(bv);
    }
    if (typeof av === 'string') return stakerSortDir * av.localeCompare(bv);
    return stakerSortDir * ((av || 0) - (bv || 0));
  });
  return rows;
}

function stakerType(s) {
  const hasVkat  = s.vkatAmount > 0;
  const hasAvkat = s.avkatAmount > 0;
  if (hasVkat && hasAvkat) return 'Both';
  if (hasVkat) return 'vKAT';
  return 'avKAT';
}

function updateStakerStats() {
  const all          = stakerData;
  const totalStaked  = all.reduce((s, d) => s + d.totalStaked, 0);
  const totalVkat    = all.reduce((s, d) => s + d.vkatAmount, 0);
  const totalAvkat   = all.reduce((s, d) => s + d.avkatAmount, 0);

  // Use on-chain contract totals for header stats (ground truth),
  // fall back to tracked-address sums if on-chain data unavailable
  const dispTotal = onChainTotal || totalStaked;
  const dispVkat  = onChainVkat  || totalVkat;
  const dispAvkat = onChainAvkat || totalAvkat;
  const pctCirc   = circSupply > 0 ? (dispTotal / circSupply * 100) : 0;
  const TOTAL_SUPPLY = 1e10;
  const pctTotal  = dispTotal > 0 ? (dispTotal / TOTAL_SUPPLY * 100) : 0;

  document.getElementById('sstat-total-staked').textContent = fmtNum(dispTotal, 0);
  setKatStatSub('sstat-total-staked', 'sstat-total-sub', dispTotal, 'on-chain');
  document.getElementById('sstat-pct-circ').textContent     = pctCirc > 0 ? pctCirc.toFixed(1) + '%' : '—';
  document.getElementById('sstat-pct-circ-sub').textContent = circSupply > 0 ? `of ${fmtNum(circSupply, 0)} circ` : '';
  document.getElementById('sstat-pct-total').textContent    = pctTotal > 0 ? pctTotal.toFixed(2) + '%' : '—';
  document.getElementById('sstat-count').textContent        = (stakerCountMeta || all.length).toLocaleString();
  document.getElementById('sstat-vkat').textContent         = fmtNum(dispVkat, 0);
  setKatStatSub('sstat-vkat', 'sstat-vkat-sub', dispVkat, vkatHolders ? `${vkatHolders.toLocaleString()} holders` : '');
  document.getElementById('sstat-avkat').textContent        = fmtNum(dispAvkat, 0);
  setKatStatSub('sstat-avkat', 'sstat-avkat-sub', dispAvkat, avkatHolders ? `${avkatHolders.toLocaleString()} holders` : '');
  const vPct = dispTotal > 0 ? (dispVkat / dispTotal * 100).toFixed(0) : 0;
  const aPct = dispTotal > 0 ? (dispAvkat / dispTotal * 100).toFixed(0) : 0;
  document.getElementById('sstat-split').textContent        = `${vPct}% / ${aPct}%`;
  let medianStake = 0;
  if (all.length > 0) {
    const sorted = all.map(d => d.totalStaked).filter(v => v > 0).sort((a, b) => a - b);
    const m = sorted.length;
    if (m > 0) medianStake = m % 2 === 1 ? sorted[(m - 1) / 2] : (sorted[m / 2 - 1] + sorted[m / 2]) / 2;
  }
  document.getElementById('sstat-median-stake').textContent = medianStake > 0 ? fmtNum(medianStake, 0) : '—';
  setKatStatSub('sstat-median-stake', 'sstat-median-stake-sub', medianStake, '');

  // 30d growth (loads snapshots.json, falls back to localStorage)
  showStakerGrowth({ totalStaked: dispTotal, pctCirc, pctTotal, count: all.length, vkat: dispVkat, avkat: dispAvkat });
}

let _stakerSnapshots = null;
function loadStakerSnapshots() {
  return fetch('snapshots.json?' + Date.now())
    .then(r => r.ok ? r.json() : {})
    .catch(() => ({}));
}
function showStakerGrowth(current) {
  const render = (snaps) => {
    _stakerSnapshots = snaps;
    // Also save today to localStorage as fallback
    const today = new Date().toISOString().slice(0, 10);
    if (current.totalStaked) snaps[today] = current;
    try { localStorage.setItem('kat_farmer_staker_snapshots', JSON.stringify(snaps)); } catch(e) {}
    _showGrowthFromSnaps(current, snaps);
  };
  if (_stakerSnapshots) { render(_stakerSnapshots); return; }
  loadStakerSnapshots().then(fileSnaps => {
    // Merge localStorage fallback (older data) under file snapshots
    try {
      const ls = JSON.parse(localStorage.getItem('kat_farmer_staker_snapshots')) || {};
      Object.keys(ls).forEach(k => { if (!fileSnaps[k]) fileSnaps[k] = ls[k]; });
    } catch(e) {}
    render(fileSnaps);
  });
}
function _showGrowthFromSnaps(current, snaps) {
  const dates = Object.keys(snaps).sort();
  if (dates.length < 2) return; // need history
  // Find snapshot closest to 30 days ago
  const target = new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10);
  let best = dates[0];
  for (const d of dates) { if (d <= target) best = d; else break; }
  const old = snaps[best];
  if (!old) return;
  const daysAgo = Math.round((Date.now() - new Date(best).getTime()) / 86400000);

  function renderGrowth(elId, curr, prev, fmt) {
    const el = document.getElementById(elId);
    if (!el || !prev) return;
    const delta = curr - prev;
    const pct = prev !== 0 ? (delta / prev * 100) : 0;
    const sign = delta > 0 ? '+' : '';
    const cls = delta > 0 ? 'up' : delta < 0 ? 'down' : 'flat';
    const arrow = delta > 0 ? '↑' : delta < 0 ? '↓' : '→';
    el.className = 'stat-growth ' + cls;
    el.textContent = `${arrow} ${sign}${fmt(delta)} (${sign}${pct.toFixed(1)}%) · ${daysAgo}d`;
  }
  const fmtK = v => Math.abs(v) >= 1e6 ? (v/1e6).toFixed(1)+'M' : Math.abs(v) >= 1e3 ? (v/1e3).toFixed(1)+'K' : v.toFixed(0);
  const fmtPct = v => v.toFixed(1) + 'pp';
  const fmtInt = v => v.toFixed(0);

  renderGrowth('sstat-total-staked-growth', current.totalStaked, old.totalStaked, fmtK);
  renderGrowth('sstat-pct-circ-growth', current.pctCirc, old.pctCirc, fmtPct);
  const oldPctTotal = old.totalStaked ? (old.totalStaked / 1e10 * 100) : null;
  renderGrowth('sstat-pct-total-growth', current.pctTotal, oldPctTotal, fmtPct);
  renderGrowth('sstat-count-growth', current.count, old.count, fmtInt);
  renderGrowth('sstat-vkat-growth', current.vkat, old.vkat, fmtK);
  renderGrowth('sstat-avkat-growth', current.avkat, old.avkat, fmtK);
}

// ---- Stakers history chart modal ----
const STAKER_METRIC_META = {
  totalStaked: { title: 'Total KAT Staked',  suffix: '',   fmt: v => fmtNum(v, 0),                 yPad: 0 },
  pctCirc:     { title: '% of Circ Supply',  suffix: '%',  fmt: v => v.toFixed(2) + '%',           yPad: 0 },
  pctTotal:    { title: '% of Total Supply', suffix: '%',  fmt: v => v.toFixed(2) + '%',           yPad: 0 },
  count:       { title: '# Stakers',          suffix: '',   fmt: v => Math.round(v).toLocaleString(), yPad: 0 },
  vkat:        { title: 'vKAT Locked',        suffix: '',   fmt: v => fmtNum(v, 0),                 yPad: 0 },
  avkat:       { title: 'avKAT Deposited',    suffix: '',   fmt: v => fmtNum(v, 0),                 yPad: 0 },
  split:       { title: 'vKAT / avKAT Split', suffix: '%',  fmt: v => v.toFixed(1) + '%',           yPad: 0 },
};
function showStakerChart(metric) {
  const modal = document.getElementById('chart-modal');
  const titleEl = document.getElementById('chart-modal-title');
  const body = document.getElementById('chart-modal-body');
  const meta = STAKER_METRIC_META[metric];
  if (!meta) return;
  titleEl.textContent = meta.title;
  body.innerHTML = '<div class="chart-empty">Loading…</div>';
  modal.classList.add('open');
  document.body.style.overflow = 'hidden';

  const render = (snaps) => {
    const dates = Object.keys(snaps).sort();
    if (dates.length < 2) {
      body.innerHTML = '<div class="chart-empty">Not enough history yet (need ≥ 2 daily snapshots).</div>';
      return;
    }
    if (metric === 'split') {
      // Two series: vKAT % and avKAT % of totalStaked
      const vSeries = [], aSeries = [];
      dates.forEach(d => {
        const s = snaps[d]; if (!s) return;
        const total = (s.vkat || 0) + (s.avkat || 0);
        if (total <= 0) return;
        vSeries.push({ date: d, value: (s.vkat  / total) * 100 });
        aSeries.push({ date: d, value: (s.avkat / total) * 100 });
      });
      if (vSeries.length < 2) { body.innerHTML = '<div class="chart-empty">Not enough valid data points.</div>'; return; }
      body.innerHTML = buildChartSVG([
        { name: 'vKAT',  points: vSeries, cls: 'c-line',   dotCls: 'c-dot'   },
        { name: 'avKAT', points: aSeries, cls: 'c-line-2', dotCls: 'c-dot-2' },
      ], { fmt: meta.fmt, yMin: 0, yMax: 100 })
      + '<div class="chart-legend">'
      +   '<span><span class="sw" style="background:var(--violet)"></span>vKAT %</span>'
      +   '<span><span class="sw" style="background:var(--accent,#e8a832)"></span>avKAT %</span>'
      + '</div>'
      + `<div class="chart-meta">${vSeries.length} snapshots · ${vSeries[0].date} → ${vSeries[vSeries.length-1].date}</div>`;
      return;
    }
    const pts = [];
    dates.forEach(d => {
      const s = snaps[d]; if (!s) return;
      let v;
      if (metric === 'pctTotal') {
        v = (s.totalStaked > 0) ? (s.totalStaked / 1e10 * 100) : null;
      } else {
        v = s[metric];
      }
      if (v === null || v === undefined || isNaN(v)) return;
      pts.push({ date: d, value: v });
    });
    if (pts.length < 2) { body.innerHTML = '<div class="chart-empty">Not enough valid data points.</div>'; return; }
    body.innerHTML = buildChartSVG([
      { name: meta.title, points: pts, cls: 'c-line', dotCls: 'c-dot', area: true },
    ], { fmt: meta.fmt })
    + `<div class="chart-meta">${pts.length} snapshots · ${pts[0].date} → ${pts[pts.length-1].date} · latest ${meta.fmt(pts[pts.length-1].value)}</div>`;
  };

  if (_stakerSnapshots) { render(_stakerSnapshots); return; }
  loadStakerSnapshots().then(fileSnaps => {
    try {
      const ls = JSON.parse(localStorage.getItem('kat_farmer_staker_snapshots')) || {};
      Object.keys(ls).forEach(k => { if (!fileSnaps[k]) fileSnaps[k] = ls[k]; });
    } catch(e) {}
    _stakerSnapshots = fileSnaps;
    render(fileSnaps);
  });
}

function buildChartSVG(series, opts) {
  // Viewbox
  const W = 680, H = 320;
  const pad = { l: 56, r: 16, t: 16, b: 32 };
  const innerW = W - pad.l - pad.r;
  const innerH = H - pad.t - pad.b;

  // Collect all dates (union, sorted). All series should share the date axis.
  const dateSet = new Set();
  series.forEach(s => s.points.forEach(p => dateSet.add(p.date)));
  const allDates = Array.from(dateSet).sort();
  const xIdx = Object.fromEntries(allDates.map((d, i) => [d, i]));
  const n = allDates.length;

  let yMin = opts.yMin, yMax = opts.yMax;
  if (yMin === undefined || yMax === undefined) {
    let lo = Infinity, hi = -Infinity;
    series.forEach(s => s.points.forEach(p => { if (p.value < lo) lo = p.value; if (p.value > hi) hi = p.value; }));
    if (lo === hi) { lo = lo - 1; hi = hi + 1; }
    const span = hi - lo;
    yMin = yMin !== undefined ? yMin : Math.max(0, lo - span * 0.08);
    yMax = yMax !== undefined ? yMax : hi + span * 0.08;
  }
  const x = i => pad.l + (n === 1 ? innerW / 2 : (i / (n - 1)) * innerW);
  const y = v => pad.t + innerH - ((v - yMin) / (yMax - yMin)) * innerH;

  // Y-axis ticks (5)
  const yTicks = [];
  for (let i = 0; i <= 4; i++) {
    const v = yMin + (yMax - yMin) * (i / 4);
    yTicks.push({ v, y: y(v) });
  }
  // X-axis ticks (~6)
  const tickCount = Math.min(6, n);
  const xTicks = [];
  for (let i = 0; i < tickCount; i++) {
    const idx = Math.round((i / (tickCount - 1)) * (n - 1));
    xTicks.push({ i: idx, label: allDates[idx].slice(5) }); // MM-DD
  }

  let svg = `<div class="chart-wrap"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid meet">`;
  // Grid + y ticks
  yTicks.forEach(t => {
    svg += `<line class="c-grid" x1="${pad.l}" y1="${t.y}" x2="${W - pad.r}" y2="${t.y}"/>`;
    svg += `<text class="c-tick" x="${pad.l - 6}" y="${t.y + 3}" text-anchor="end">${opts.fmt(t.v)}</text>`;
  });
  // Axes
  svg += `<line class="c-axis" x1="${pad.l}" y1="${pad.t}" x2="${pad.l}" y2="${H - pad.b}"/>`;
  svg += `<line class="c-axis" x1="${pad.l}" y1="${H - pad.b}" x2="${W - pad.r}" y2="${H - pad.b}"/>`;
  // X ticks
  xTicks.forEach(t => {
    const xp = x(t.i);
    svg += `<text class="c-tick" x="${xp}" y="${H - pad.b + 14}" text-anchor="middle">${t.label}</text>`;
  });

  // Series lines + area + dots
  series.forEach(s => {
    const path = s.points.map((p, i) => {
      const xp = x(xIdx[p.date]);
      const yp = y(p.value);
      return (i === 0 ? 'M' : 'L') + xp.toFixed(1) + ' ' + yp.toFixed(1);
    }).join(' ');
    if (s.area) {
      const first = s.points[0], last = s.points[s.points.length - 1];
      const areaPath = path
        + ` L ${x(xIdx[last.date]).toFixed(1)} ${(H - pad.b).toFixed(1)}`
        + ` L ${x(xIdx[first.date]).toFixed(1)} ${(H - pad.b).toFixed(1)} Z`;
      svg += `<path class="c-area" d="${areaPath}"/>`;
    }
    svg += `<path class="${s.cls}" d="${path}"/>`;
    s.points.forEach(p => {
      const xp = x(xIdx[p.date]);
      const yp = y(p.value);
      svg += `<circle class="${s.dotCls}" cx="${xp.toFixed(1)}" cy="${yp.toFixed(1)}" r="3"/>`;
    });
  });

  // Hover layer: crosshair + enlarged dot per series + transparent hit area
  svg += `<line class="c-crosshair" x1="0" y1="${pad.t}" x2="0" y2="${H - pad.b}" style="display:none"/>`;
  series.forEach((s, i) => {
    svg += `<circle class="c-hover-dot ${s.dotCls}" data-sidx="${i}" cx="0" cy="0" r="5" style="display:none"/>`;
  });
  svg += `<rect class="c-hover-area" x="${pad.l}" y="${pad.t}" width="${innerW}" height="${innerH}" fill="transparent"/>`;
  svg += `</svg><div class="c-tooltip" style="display:none"></div></div>`;

  // Stash data for attachChartHover (called on next tick, after innerHTML assignment).
  const xByDate = {};
  allDates.forEach(d => xByDate[d] = x(xIdx[d]));
  const ptsByDate = {};
  allDates.forEach(d => ptsByDate[d] = []);
  series.forEach(s => {
    s.points.forEach(p => {
      ptsByDate[p.date].push({ series: s.name, value: p.value, y: y(p.value) });
    });
  });
  window._chartHoverData = {
    allDates, xByDate, ptsByDate,
    W, H, pad,
    seriesMeta: series.map(s => ({ name: s.name, cls: s.dotCls })),
    fmt: opts.fmt,
  };
  setTimeout(attachChartHover, 0);

  return svg;
}


// ---- Stakers distribution histogram ----
const STAKE_BUCKETS = [
  { lo: 100,  hi: 500,       label: '100–500'    },
  { lo: 500,  hi: 1e3,       label: '500–1K'     },
  { lo: 1e3,  hi: 5e3,       label: '1K–5K'      },
  { lo: 5e3,  hi: 1e4,       label: '5K–10K'     },
  { lo: 1e4,  hi: 5e4,       label: '10K–50K'    },
  { lo: 5e4,  hi: 1e5,       label: '50K–100K'   },
  { lo: 1e5,  hi: 5e5,       label: '100K–500K'  },
  { lo: 5e5,  hi: 1e6,       label: '500K–1M'    },
  { lo: 1e6,  hi: Infinity,  label: '1M+'        },
];
function showStakerHistogram() {
  const modal = document.getElementById('chart-modal');
  const titleEl = document.getElementById('chart-modal-title');
  const body = document.getElementById('chart-modal-body');
  titleEl.textContent = 'Stake Distribution';
  if (!stakerData || stakerData.length === 0) {
    body.innerHTML = '<div class="chart-empty">No staker data loaded.</div>';
    modal.classList.add('open');
    document.body.style.overflow = 'hidden';
    return;
  }
  const buckets = STAKE_BUCKETS.map(b => ({ ...b, count: 0 }));
  stakerData.forEach(d => {
    const v = d.totalStaked;
    if (!(v > 0)) return;
    for (const b of buckets) {
      if (v >= b.lo && v < b.hi) { b.count += 1; break; }
    }
  });
  const total = stakerData.filter(d => d.totalStaked > 0).length;
  body.innerHTML = buildHistogramSVG(buckets, total);
  modal.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function buildHistogramSVG(buckets, total) {
  const W = 680, H = 320;
  const pad = { l: 56, r: 16, t: 24, b: 48 };
  const innerW = W - pad.l - pad.r;
  const innerH = H - pad.t - pad.b;
  const n = buckets.length;
  const maxCount = Math.max(1, ...buckets.map(b => b.count));
  // Round yMax up to a nice number.
  const niceMax = (v) => {
    if (v <= 10) return Math.ceil(v / 2) * 2;
    const exp = Math.pow(10, Math.floor(Math.log10(v)));
    return Math.ceil(v / exp) * exp;
  };
  const yMax = niceMax(maxCount * 1.1);
  const barGap = 0.18;
  const bandW = innerW / n;
  const barW = bandW * (1 - barGap);
  const y = v => pad.t + innerH - (v / yMax) * innerH;

  const yTicks = [];
  for (let i = 0; i <= 4; i++) {
    const v = Math.round(yMax * i / 4);
    yTicks.push({ v, y: y(v) });
  }

  let svg = `<div class="chart-wrap"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid meet">`;
  yTicks.forEach(t => {
    svg += `<line class="c-grid" x1="${pad.l}" y1="${t.y}" x2="${W - pad.r}" y2="${t.y}"/>`;
    svg += `<text class="c-tick" x="${pad.l - 6}" y="${t.y + 3}" text-anchor="end">${t.v.toLocaleString()}</text>`;
  });
  svg += `<line class="c-axis" x1="${pad.l}" y1="${pad.t}" x2="${pad.l}" y2="${H - pad.b}"/>`;
  svg += `<line class="c-axis" x1="${pad.l}" y1="${H - pad.b}" x2="${W - pad.r}" y2="${H - pad.b}"/>`;

  buckets.forEach((b, i) => {
    const cx = pad.l + bandW * i + bandW / 2;
    const x0 = cx - barW / 2;
    const yTop = y(b.count);
    const hBar = (H - pad.b) - yTop;
    svg += `<rect x="${x0.toFixed(1)}" y="${yTop.toFixed(1)}" width="${barW.toFixed(1)}" height="${hBar.toFixed(1)}" fill="var(--violet)" stroke="var(--black)" stroke-width="1"/>`;
    if (b.count > 0) {
      const pct = total > 0 ? ((b.count / total) * 100).toFixed(1) : '0';
      svg += `<text class="c-tick" x="${cx}" y="${(yTop - 6).toFixed(1)}" text-anchor="middle" style="font-weight:700">${b.count.toLocaleString()}</text>`;
      svg += `<text class="c-tick" x="${cx}" y="${(yTop - 6 + 12).toFixed(1)}" text-anchor="middle" style="opacity:0.65">${pct}%</text>`;
    }
    svg += `<text class="c-tick" x="${cx}" y="${(H - pad.b + 16).toFixed(1)}" text-anchor="middle">${b.label}</text>`;
    svg += `<text class="c-tick" x="${cx}" y="${(H - pad.b + 30).toFixed(1)}" text-anchor="middle" style="opacity:0.6">KAT</text>`;
  });

  svg += `</svg></div>`;
  svg += `<div class="chart-meta">${total.toLocaleString()} wallets · buckets are KAT staked (vKAT + avKAT)</div>`;
  return svg;
}

function attachChartHover() {
  const wrap = document.querySelector('#chart-modal .chart-wrap');
  const data = window._chartHoverData;
  if (!wrap || !data) return;
  const svg   = wrap.querySelector('svg');
  const area  = wrap.querySelector('.c-hover-area');
  const cross = wrap.querySelector('.c-crosshair');
  const dots  = wrap.querySelectorAll('.c-hover-dot');
  const tip   = wrap.querySelector('.c-tooltip');
  if (!area || !svg || !cross || !tip) return;

  const multi = data.seriesMeta.length > 1;

  const move = (ev) => {
    const rect = svg.getBoundingClientRect();
    if (rect.width <= 0) return;
    const vbX = ((ev.clientX - rect.left) / rect.width) * data.W;
    // nearest date by x-distance
    let nearest = null, best = Infinity;
    for (const d of data.allDates) {
      const dx = Math.abs(vbX - data.xByDate[d]);
      if (dx < best) { best = dx; nearest = d; }
    }
    if (!nearest) return;

    const xp  = data.xByDate[nearest];
    const pts = data.ptsByDate[nearest];
    cross.setAttribute('x1', xp);
    cross.setAttribute('x2', xp);
    cross.style.display = '';

    dots.forEach((dot, i) => {
      const p = pts[i];
      if (!p) { dot.style.display = 'none'; return; }
      dot.setAttribute('cx', xp);
      dot.setAttribute('cy', p.y);
      dot.style.display = '';
    });

    const rows = pts.map(p => {
      const label = multi ? `<span class="t-ser">${p.series}</span> ` : '';
      return `<div>${label}<b>${data.fmt(p.value)}</b></div>`;
    }).join('');
    tip.innerHTML = `<div class="t-date">${nearest}</div>${rows}`;

    // position tooltip: above highest dot for this date, centered on xp
    const topY = Math.min(...pts.map(p => p.y));
    const scale = rect.width / data.W;
    const pxX   = xp * scale;
    const pxY   = topY * scale;
    const wrapRect = wrap.getBoundingClientRect();
    const baseLeft = rect.left - wrapRect.left;
    const baseTop  = rect.top  - wrapRect.top;
    tip.style.display = '';
    // After first render, we know tooltip size → reposition to center above
    const tw = tip.offsetWidth;
    const th = tip.offsetHeight;
    let left = baseLeft + pxX - tw / 2;
    let top  = baseTop + pxY - th - 10;
    // clamp horizontally within chart-wrap
    const maxLeft = wrap.clientWidth - tw - 4;
    if (left < 4) left = 4;
    if (left > maxLeft) left = maxLeft;
    if (top < 4) top = baseTop + pxY + 14; // flip below if not enough room above
    tip.style.left = left + 'px';
    tip.style.top  = top  + 'px';
  };

  const leave = () => {
    cross.style.display = 'none';
    dots.forEach(d => d.style.display = 'none');
    tip.style.display = 'none';
  };

  area.addEventListener('pointermove', move);
  area.addEventListener('pointerleave', leave);
}

function renderStakersTable() {
  if (document.querySelector('.label-input')) return;
  const rows    = getStakerFilteredRows();
  const countEl = document.getElementById('staker-table-count');
  countEl.textContent = stakerFilterText
    ? `${rows.length} / ${stakerData.length}`
    : `${stakerData.length.toLocaleString()} stakers`;

  const tbody = document.getElementById('staker-table-body');
  if (stakerData.length === 0) {
    tbody.innerHTML = '<tr class="loading-row"><td colspan="7">No staker data — run: python3 indexer.py --full</td></tr>';
    return;
  }
  if (rows.length === 0) {
    tbody.innerHTML = '<tr class="loading-row"><td colspan="7">No matching stakers</td></tr>';
    return;
  }

  tbody.innerHTML = rows.map((s, i) => {
    const type = stakerType(s);
    const typeBadge = type === 'Both'
      ? '<span class="badge" style="background:var(--violet);color:#fff" data-tip="Both voting escrow (vKAT) and auto-compounding vault (avKAT)">Both</span>'
      : type === 'vKAT'
        ? '<span class="badge" style="background:#9933ff;color:#fff" data-tip="Locked KAT in voting escrow — long-term conviction">vKAT</span>'
        : '<span class="badge" style="background:#b366ff;color:#fff" data-tip="Deposited KAT in auto-compounding vault">avKAT</span>';
    return `<tr>
      <td>${i + 1}</td>
      <td class="addr-cell" onclick="editLabel(this,'${s.address}')" title="Click to label">
        ${addrDisplay(s.address)}
      </td>
      <td class="num">${s.vkatAmount > 0 ? `<span class="num-blue">${fmtNum(s.vkatAmount)}</span>` : '—'}</td>
      <td class="num">${s.avkatAmount > 0 ? `<span class="num-blue">${fmtNum(s.avkatAmount)}</span>` : '—'}</td>
      <td class="num"><span class="num-blue">${fmtNum(s.totalStaked)}</span></td>
      <td>${typeBadge}</td>
      <td>
        <div class="ext-links">
          <a class="ext-link" href="https://katanascan.com/address/${s.address}" target="_blank" rel="noopener">explr</a>
          <a class="ext-link" href="#" onclick="navigator.clipboard.writeText('${s.address}');this.textContent='✓';setTimeout(()=>this.textContent='⎘',1200);return false;" title="Copy address">⎘</a>
        </div>
      </td>
    </tr>`;
  }).join('');
}

function exportStakerCSV() {
  const rows   = getStakerFilteredRows();
  const header = ['Address','vKAT Amount','avKAT Amount','Total Staked','Type'];
  const lines  = rows.map(s => [
    s.address,
    s.vkatAmount.toFixed(6),
    s.avkatAmount.toFixed(6),
    s.totalStaked.toFixed(6),
    stakerType(s),
  ].join(','));
  const csv  = [header.join(','), ...lines].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);
  Object.assign(document.createElement('a'), { href: url, download: 'kat-stakers.csv' }).click();
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}

// ── SUPPLY TAB ───────────────────────────────────────────────────────────────
const PROTO_COLORS = {
  'Katana Vaults': '--blue',
  'SushiSwap':     '--amber',
  'Yearn':         '--violet',
  'Charm':         '--orange',
  'Morpho':        '--green',
  'other':         '--dim',
};
const PROTO_URLS = {};

function fmtM(n) {
  if (n >= 1e9) return (n / 1e9).toFixed(2) + 'B';
  if (n >= 1e6) return (n / 1e6).toFixed(2) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(1) + 'K';
  return n.toFixed(0);
}

function renderSupplyTab(d) {
  // Hero
  document.getElementById('supply-hero-pct').textContent = d.circulatingPct.toFixed(2) + '%';
  const _heroEl = document.getElementById('supply-hero-total');
  _heroEl.textContent = fmtM(d.totalCirculating) + ' KAT in circulation';
  _katCache['supply-hero-total'] = { kat: d.totalCirculating, baseSub: 'in circulation', prefix: fmtM(d.totalCirculating) + ' KAT' };
  refreshOneKatSub('supply-hero-total');

  const s = d.sources;
  const mix = d.protocolMix || {};
  const merklTotal = s.merkl.amount;
  const totalSupply = d.totalSupply;
  const sorted = Object.entries(mix).sort((a, b) => b[1].frac - a[1].frac);

  // Build table rows
  const tbody = document.getElementById('supply-table-body');
  tbody.innerHTML = '';
  const rows = [];

  // Merkl protocol sub-rows
  if (sorted.length > 0) {
    sorted.forEach(([name, info]) => {
      const amt = info.frac * merklTotal;
      const pctSupply = (amt / totalSupply * 100).toFixed(2);
      const color = PROTO_COLORS[name] || '--dim';
      let detail = '';
      if (info.subs && Object.keys(info.subs).length > 0) {
        detail = Object.entries(info.subs).sort((a,b) => b[1]-a[1]).map(([s,f]) => `${escapeHtml(s)} ${(f*100).toFixed(0)}%`).join(', ');
      }
      const url = PROTO_URLS[name];
      const nameHtml = url
        ? `<span style="color:var(${color})">■</span> <a class="ext-link" href="${url}" target="_blank" rel="noopener">${escapeHtml(name)}</a>`
        : `<span style="color:var(${color})">■</span> ${escapeHtml(name)}`;
      rows.push({ nameHtml, amt, pctSupply, detail });
    });
  } else {
    rows.push({
      nameHtml: '<b>Merkl Rewards</b>',
      amt: s.merkl.amount,
      pctSupply: s.merkl.pct.toFixed(2),
      detail: 'Protocol breakdown unavailable',
    });
  }

  // Merkl total row
  const merklRow = document.createElement('tr');
  merklRow.style.cssText = 'border-top:2px solid var(--black);font-weight:700;';
  merklRow.innerHTML = `<td><b>Merkl Total</b></td><td class="num">${fmtM(s.merkl.amount)}</td><td class="num">${s.merkl.pct.toFixed(2)}%</td><td></td>`;

  // Fixed allocation rows (vaults + TGE sources — everything except merkl)
  const fixedRows = Object.entries(s)
    .filter(([k, v]) => k !== 'merkl' && v.type === 'fixed')
    .map(([k, v]) => ({ name: v.label, amount: v.amount, pct: v.pct, desc: v.desc, subs: v.subs }));

  // Render protocol rows
  rows.forEach(r => {
    const tr = document.createElement('tr');
    tr.innerHTML = `<td>${r.nameHtml}</td><td class="num">${fmtM(r.amt)}</td><td class="num">${r.pctSupply}%</td><td style="color:var(--dim);font-size:0.78rem">${r.detail}</td>`;
    tbody.appendChild(tr);
  });

  tbody.appendChild(merklRow);

  fixedRows.forEach((v, i) => {
    const hasSubs = v.subs && v.subs.length > 0;
    const tr = document.createElement('tr');
    const detail = v.desc || 'Fixed allocation';
    if (hasSubs) {
      tr.className = 'supply-parent';
      tr.dataset.group = `fixed-${i}`;
      tr.onclick = () => {
        tr.classList.toggle('open');
        document.querySelectorAll(`tr.supply-child[data-group="fixed-${i}"]`).forEach(c => c.classList.toggle('visible'));
      };
    }
    tr.innerHTML = `<td><b>${escapeHtml(v.name)}</b></td><td class="num">${fmtM(v.amount)}</td><td class="num">${v.pct.toFixed(2)}%</td><td style="color:var(--dim);font-size:0.78rem">${escapeHtml(detail)}</td>`;
    tbody.appendChild(tr);
    if (hasSubs) {
      v.subs.forEach(sub => {
        const sr = document.createElement('tr');
        sr.className = 'supply-child';
        sr.dataset.group = `fixed-${i}`;
        sr.innerHTML = `<td>${escapeHtml(sub.name)}</td><td class="num">${fmtM(sub.amount)}</td><td class="num">${sub.pct.toFixed(2)}%</td><td></td>`;
        tbody.appendChild(sr);
      });
    }
  });

  const totalRow = document.createElement('tr');
  totalRow.style.cssText = 'border-top:2px solid var(--black);font-weight:700;background:var(--cream2);';
  totalRow.innerHTML = `<td><b>Total Circulating</b></td><td class="num">${fmtM(d.totalCirculating)}</td><td class="num">${d.circulatingPct.toFixed(2)}%</td><td></td>`;
  tbody.appendChild(totalRow);
}

async function loadSupplyData() {
  try {
    const resp = await fetch('supply_data.json?' + Date.now());
    if (!resp.ok) return;
    const d = await resp.json();
    renderSupplyTab(d);
  } catch (e) {
    console.error('Supply data fetch failed:', e.message);
  }
}

// ── MAIN ──────────────────────────────────────────────────────────────────────
async function main() {
  fetchKatPrice();
  // Restore UI from URL state
  const filterInput  = document.getElementById('filter-input');
  const statusSelect = document.getElementById('status-filter');
  const minSelect    = document.getElementById('min-filter');

  if (filterText)   filterInput.value  = filterText;
  if (filterStatus) syncSelectUI('status-filter', filterStatus);
  if (minAmount)    syncSelectUI('min-filter', String(minAmount));

  // Restore top-N active state
  if (topN > 0) {
    document.querySelectorAll('.top-btn').forEach(b => {
      if (+b.dataset.n === topN) b.classList.add('active');
    });
  }

  // Restore active stat card
  if (filterStatus) {
    document.querySelectorAll('.stat-card[data-filter]').forEach(c => {
      if (c.dataset.filter === filterStatus) c.classList.add('active');
    });
  }

  // Event listeners
  filterInput.addEventListener('input', e => {
    filterText = e.target.value.trim();
    scheduleRender();
    pushState();
  });

  statusSelect.addEventListener('change', e => {
    filterStatus = e.target.value;
    document.querySelectorAll('.stat-card[data-filter]').forEach(c => c.classList.remove('active'));
    if (filterStatus) {
      const card = document.querySelector(`.stat-card[data-filter="${filterStatus}"]`);
      if (card) card.classList.add('active');
    }
    scheduleRender();
    pushState();
  });

  minSelect.addEventListener('change', e => {
    minAmount = +e.target.value || 0;
    scheduleRender();
    pushState();
  });

  initCustomSelects();

  // Tab switching — persist in URL hash
  function switchTab(tab) {
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));
    const btn = document.querySelector(`.tab-btn[data-tab="${tab}"]`);
    if (btn) btn.classList.add('active');
    const pane = document.getElementById('tab-' + tab);
    if (pane) pane.classList.add('active');
    history.replaceState(null, '', '#' + tab);
  }
  document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', () => switchTab(btn.dataset.tab));
  });
  // Restore tab from URL hash on load
  const hashTab = location.hash.replace('#', '');
  if (hashTab && document.getElementById('tab-' + hashTab)) {
    switchTab(hashTab);
  }

  // Stat card click filters
  document.querySelectorAll('.stat-card[data-filter]').forEach(card => {
    card.addEventListener('click', () => {
      const f = card.dataset.filter;
      filterStatus = (filterStatus === f) ? '' : f;
      syncSelectUI('status-filter', filterStatus);
      document.querySelectorAll('.stat-card[data-filter]').forEach(c => c.classList.remove('active'));
      if (filterStatus) card.classList.add('active');
      scheduleRender();
      pushState();
    });
  });

  // Top-N buttons
  document.querySelectorAll('.top-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const n = +btn.dataset.n;
      if (topN === n) {
        topN = 0;
        btn.classList.remove('active');
      } else {
        topN = n;
        document.querySelectorAll('.top-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
      }
      scheduleRender();
      pushState();
    });
  });

  document.getElementById('export-btn').addEventListener('click', exportCSV);
  document.getElementById('export-labels-btn').addEventListener('click', exportLabels);
  document.getElementById('reload-btn').addEventListener('click', e => {
    e.target.disabled = true;
    e.target.textContent = '↺ Loading…';
    location.reload();
  });

  filterInput.addEventListener('keydown', e => {
    if (e.key === 'Escape') { filterInput.value = ''; filterText = ''; filterInput.blur(); scheduleRender(); pushState(); }
  });
  document.addEventListener('keydown', e => {
    if (e.key === '/' && document.activeElement !== filterInput && document.activeElement.tagName !== 'INPUT') {
      e.preventDefault();
      filterInput.focus();
    }
  });

  document.querySelectorAll('th[data-col]').forEach(th => {
    th.addEventListener('click', () => {
      const col = th.dataset.col;
      if (sortCol === col) { sortDir *= -1; }
      else { sortCol = col; sortDir = (col === 'address' || col === 'status') ? 1 : -1; }
      document.querySelectorAll('th[data-col]').forEach(t => {
        t.classList.remove('sorted');
        t.querySelector('.sort-arrow').textContent = '';
      });
      th.classList.add('sorted');
      th.querySelector('.sort-arrow').textContent = sortDir === -1 ? '↓' : '↑';
      scheduleRender();
      pushState();
    });
  });

  // Restore sort arrow from URL state
  if (sortCol) {
    const th = document.querySelector(`th[data-col="${sortCol}"]`);
    if (th) {
      document.querySelectorAll('th[data-col]').forEach(t => {
        t.classList.remove('sorted');
        t.querySelector('.sort-arrow').textContent = '';
      });
      th.classList.add('sorted');
      th.querySelector('.sort-arrow').textContent = sortDir === -1 ? '↓' : '↑';
    }
  }

  // Load addresses, CEX wallets, and labels from addresses.json
  const addrResp = await fetch('addresses.json?' + Date.now());
  if (addrResp.ok) {
    const addrData = await addrResp.json();
    ADDRESSES_RAW = addrData.addresses || [];
    CEX_WALLETS_SET = new Set(addrData.cex_wallets || []);
    CEX_LABELS_MAP = addrData.cex_labels || {};
  }

  // Load pre-computed data from indexer.py output
  document.getElementById('progress-label').innerHTML = 'Loading data.json…';
  let data;
  try {
    const resp = await fetch('data.json?' + Date.now());
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    data = await resp.json();
  } catch (err) {
    const el = document.getElementById('error-msg');
    el.textContent = 'Failed to load data.json — run: python3 indexer.py';
    el.style.display = 'block';
    document.getElementById('progress-section').style.display = 'none';
    return;
  }

  // Build stakerMap before processing addresses so d.staked is correct
  stakerData = data.stakers || [];
  stakerMap = {}; for (const s of stakerData) stakerMap[s.address] = s;

  ADDRESSES = data.addresses.map(d => d.address);
  for (const d of data.addresses) {
    ingestAddress(d);
  }

  const generatedAt = data.meta?.generatedAt ? new Date(data.meta.generatedAt) : null;
  const timeStr = generatedAt
    ? generatedAt.toLocaleString('en-GB', { timeZone: 'UTC', year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) + ' UTC'
    : 'unknown';
  const labelCount = Object.keys(CEX_LABELS_MAP).length + Object.keys(LABELS).length;
  document.getElementById('stat-addr-count').textContent = `${labelCount} labelled`;
  document.getElementById('stat-snapshot-sub').textContent = `${ADDRESSES.length} scanned · ${timeStr}`;
  document.getElementById('progress-section').style.display = 'none';
  lastGeneratedAt = generatedAt;
  updateFreshnessIndicator();

  updateStats();
  scheduleRender();

  // ── Labels (non-blocking, best-effort) ──────────────────────────────────
  fetch('labels.json?' + Date.now())
    .then(r => r.ok ? r.json() : null)
    .then(obj => { if (obj && typeof obj === 'object') { Object.assign(LABELS, obj); scheduleRender(); } })
    .catch(() => {});

  // ── Supply tab (parallel — doesn't block other tabs)
  loadSupplyData();

  // ── Auto-refresh polling (every 5 minutes) ────────────────────────────────
  setInterval(async () => {
    try {
      // Skip refresh if user is editing a label
      if (document.querySelector('.label-input')) return;
      const resp = await fetch('data.json?' + Date.now());
      if (!resp.ok) return;
      const newData = await resp.json();
      if (!newData.meta?.generatedAt) return;
      const newTs = new Date(newData.meta.generatedAt);
      if (isNaN(newTs.getTime())) return;
      if (!lastGeneratedAt || newTs > lastGeneratedAt) {
        ADDRESSES = newData.addresses.map(d => d.address);
        buyerData = newData.buyers || [];
        buyerAddrs = new Set(buyerData.map(b => b.address));
        stakerData = newData.stakers || [];
        stakerMap = {}; for (const s of stakerData) stakerMap[s.address] = s;
        for (const d of newData.addresses) { ingestAddress(d); }
        lastGeneratedAt = newTs;
        updateStats();
        updateBuyerStats();
        updateStakerStats();
        scheduleRender();
        updateFreshnessIndicator();
      }
    } catch(e) { /* silent fail — next poll retries */ }
  }, 5 * 60 * 1000);

  // ── Buyers section ────────────────────────────────────────────────────────
  buyerData  = data.buyers || [];
  buyerAddrs = new Set(buyerData.map(b => b.address));
  updateBuyerStats();
  renderBuyersTable();

  document.getElementById('buyer-filter-input').addEventListener('input', e => {
    buyerFilterText = e.target.value.trim().toLowerCase();
    renderBuyersTable();
  });

  document.querySelectorAll('.buyer-cat-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      buyerCatFilter = btn.dataset.cat;
      document.querySelectorAll('.buyer-cat-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      renderBuyersTable();
    });
  });

  document.querySelectorAll('.buyer-stake-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      buyerStakeFilter = btn.dataset.stake;
      document.querySelectorAll('.buyer-stake-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      renderBuyersTable();
    });
  });

  document.querySelectorAll('[data-bfilter]').forEach(card => {
    card.addEventListener('click', () => {
      const f = card.dataset.bfilter;
      if (f === 'staked') {
        buyerStakeFilter = (buyerStakeFilter === 'staked') ? '' : 'staked';
        document.querySelectorAll('.buyer-stake-btn').forEach(b => {
          b.classList.toggle('active', b.dataset.stake === buyerStakeFilter);
        });
      } else {
        buyerCatFilter = (buyerCatFilter === f) ? '' : f;
        document.querySelectorAll('.buyer-cat-btn').forEach(b => {
          b.classList.toggle('active', b.dataset.cat === buyerCatFilter);
        });
      }
      renderBuyersTable();
    });
  });

  document.getElementById('buyer-bot-btn').addEventListener('click', () => {
    buyerBotFilter = !buyerBotFilter;
    document.getElementById('buyer-bot-btn').classList.toggle('active', buyerBotFilter);
    renderBuyersTable();
  });

  document.getElementById('buyer-export-btn').addEventListener('click', exportBuyerCSV);

  document.querySelectorAll('th[data-bcol]').forEach(th => {
    th.addEventListener('click', () => {
      const col = th.dataset.bcol;
      if (buyerSortCol === col) { buyerSortDir *= -1; }
      else { buyerSortCol = col; buyerSortDir = (col === 'address' || col === 'category') ? 1 : -1; }
      document.querySelectorAll('th[data-bcol]').forEach(t => {
        t.classList.remove('sorted');
        t.querySelector('.sort-arrow').textContent = '';
      });
      th.classList.add('sorted');
      th.querySelector('.sort-arrow').textContent = buyerSortDir === -1 ? '↓' : '↑';
      renderBuyersTable();
    });
  });

  // ── Stakers section ────────────────────────────────────────────────────────
  stakerData   = data.stakers || [];
  stakerMap = {}; for (const s of stakerData) stakerMap[s.address] = s;
  for (const addr in results) { const d = results[addr]; const sk = stakerMap[d.address]; d.staked = sk ? (sk.vkatAmount || 0) + (sk.avkatAmount || 0) : (d.avkat || 0); }
  circSupply   = data.meta?.circSupply   || 0;
  onChainVkat  = data.meta?.onChainVkat  || 0;
  onChainAvkat = data.meta?.onChainAvkat || 0;
  onChainTotal = data.meta?.onChainTotal || 0;
  vkatHolders     = data.meta?.vkatHolders  || 0;
  avkatHolders    = data.meta?.avkatHolders || 0;
  stakerCountMeta = data.meta?.stakerCount  || 0;
  updateStakerStats();
  renderStakersTable();

  document.getElementById('staker-filter-input').addEventListener('input', e => {
    stakerFilterText = e.target.value.trim().toLowerCase();
    renderStakersTable();
  });

  document.getElementById('staker-export-btn').addEventListener('click', exportStakerCSV);

  document.querySelectorAll('th[data-scol]').forEach(th => {
    th.addEventListener('click', () => {
      const col = th.dataset.scol;
      if (stakerSortCol === col) { stakerSortDir *= -1; }
      else { stakerSortCol = col; stakerSortDir = (col === 'address' || col === 'type') ? 1 : -1; }
      document.querySelectorAll('th[data-scol]').forEach(t => {
        t.classList.remove('sorted');
        t.querySelector('.sort-arrow').textContent = '';
      });
      th.classList.add('sorted');
      th.querySelector('.sort-arrow').textContent = stakerSortDir === -1 ? '↓' : '↑';
      renderStakersTable();
    });
  });
}
main().catch(err => {
  const el = document.getElementById('error-msg');
  el.textContent = 'Error: ' + err.message;
  el.style.display = 'block';
});